apiVersion: v1
kind: Secret
metadata:
  name: assignment-mysql-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "assignment.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_DATABASE: {{ .Values.mysql.database | quote }}
  MYSQL_USER: {{ .Values.mysql.username | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
