apiVersion: v1
kind: Service
metadata:
  name: gov-permits-rest
  namespace: minikube-demo
  labels:
    app: gov-permits-rest
    lab: government-services
spec:
  type: ClusterIP
  selector:
    app: gov-permits-rest
  ports:
    - name: http
      port: 8080
      targetPort: 8080
