namespace: minikube-demo

mysql:
  image: mysql:8.4
  database: gov_services
  username: gov_user
  password: gov_pass_ChangeMe
  rootPassword: root_pass_ChangeMe
  storage: 2Gi

mi:
  enabled: true
  image: docker.io/wso2/wso2mi:4.6.0
  replicas: 1
  serviceName: assignment-mi
  mysqlConnector:
    image: curlimages/curl:8.10.1
    url: https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/9.0.0/mysql-connector-j-9.0.0.jar
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 1536Mi

apim:
  enabled: true
  namespace: wso2
  image: docker.io/wso2/wso2am@sha256:cd69005240af25042e8cd6eccce8fbe9341732bc887b919395c7aaddb43f8d53
  serviceName: assignment-apim
  managementHost: am.wso2.com
  gatewayHost: gw.wso2.com
  oauth2JwksUrl: https://localhost:9443/oauth2/jwks
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi

identityServer:
  enabled: true
  namespace: wso2-iam
  image: docker.io/wso2/wso2is:7.0.0
  serviceName: assignment-is
  hostname: localhost
  basePath: https://localhost
  httpsProxyPort: 443
  resources:
    requests:
      cpu: 500m
      memory: 1536Mi
    limits:
      cpu: "1"
      memory: 3Gi

client:
  localUrl: http://localhost:3000
  gatewayInvokeBaseUrl: https://gw.wso2.com:8243/gov/services/v1
