apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx-nodeport
  namespace: minikube-demo
  labels:
    app: hello-nginx-nodeport
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-nginx-nodeport
  template:
    metadata:
      labels:
        app: hello-nginx-nodeport
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
