apiVersion: v1
kind: Service
metadata:
  name: hello-nginx-nodeport
  namespace: minikube-demo
spec:
  type: NodePort
  selector:
    app: hello-nginx-nodeport
  ports:
    - name: http
      port: 80
      targetPort: 80
